### ISSUE TITLE
The contract could not be saved message

### ISSUE THREAD

**Issue by WjohnsonKPN** [zkeene/qualitydb#20] opened 2019-04-05 19:10 UTC
The contract could not be saved message

PARAVATI, ANTHONY JOSEPH  $20k 8-7-18, $30k 8-7-19

**Comment by zkeene** [comment] 2019-04-05 23:27
related to issue #6

**Comment by zkeene** [comment] 2019-04-05 23:30
Duplicate of #19

**Closed by zkeene** 2019-04-05 23:30 UTC
Labels: bug, duplicate
